name: Mirror Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push to mirror
        run: |
          git remote add mirror https://github.com/The-Geneps-Personnal-Project/ZenScript.git
          git push mirror ${GITHUB_REF:11} --force
        env:
          GITHUB_TOKEN: ${{ secrets.MIRROR_PAT }}
